baseurl = "http://tintrongnguyen.me/"
title = "after 2 beers"
paginate = 5 # The number of posts to show before paginating
theme = "ghostwriter"
enableRobotsTXT = true
googleAnalytics = ""
#SectionPagesMenu = "main"
languageCode = "en-us"
copyright = "T NG"
disqusShortname = "engineerlearnstowrite"

[Author]
    name = "T NG"
    profile = "http://tintrongnguyen.me/page/about"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    HeaderUsername = "iam"
    HeaderHostname = "tintrongnguyen"
    headline = "after 2 beers blogging"
    author = "Tin NG"
    show_menu = true 
    powered_by = true
    description = "Possibly quit coding and invest in writing in the next 10 years."
    
    github = "https://github.com/v36372"
    twitter = "https://twitter.com/v36372"

[Permalinks]
    post = "posts/:year:month:day/:filename/"
  
[[menu.main]]
    name = "blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "about"
    url = "/page/about/"
    weight = 3
