baseurl = "http://tintrongnguyen.me/"
title = "Tin Ng's Personal blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Tin Nguyen"
disqusShortname = "Tech"

[Author]
    name = "Tin Nguyen"
    profile = "http://tintrongnguyen.me/about"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Warning"
    description = "Adultery contents ahead. Please take cautions."
    github = "https://github.com/v36372"
    linkedin = "https://linkedin.com/in/tin-nguyen-trong-01448197/"
    twitter = "https://twitter.com/v36372"

[Permalinks]
    post = "posts/:year:month:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3